nav:
  - name: 时间线
    link: posts/
    target: _self
  - name: 一瞬间
    link: cards/
    target: _self
  - name: 看到的
    link: library/
    target: _self
  - name: 关于我
    link: about/
    target: _self
footerInternalLinks:
  - name: 关注
    link: linkroll/
  - name: 赞助
    link: sponsor/
