author: xiaoweige
mainSections:
  - posts
  - library
favicon: /favicon.png

# 分类页面布局配置
categoryLayout:
  columns: 3  # 每行显示的分类数量 (2, 3, 4)
extraCSSFiles:
  - /pagefind/pagefind-ui.css
externalJSFiles:
  - /js/littlefoot.js
  - /pagefind/pagefind-ui.js
footerExternalLinks:
  - name: GitHub
    link: https://github.com/pawaovo/xiaoweigeblog
    icon: https://image.guhub.cn/uPic/2025/01/NqL5b5.png
# giscus 评论系统配置 - 需要您创建自己的 GitHub 仓库后配置
# giscus:
#   repo: yourusername/yourblog
#   repoId: YOUR_REPO_ID
#   category: General
#   categoryId: YOUR_CATEGORY_ID
#   mapping: og:title
#   strict: 1
#   reactionsEnabled: 0
#   emitMetadata: 0
#   inputPosition: top
#   theme: "https://blog.xiaoweigezzz.xyz/css/giscus_noborder.css"
