author: xiaoweige
mainSections:
  - posts
  - library
favicon: /head_face_cropped.svg

# 分类页面布局配置
categoryLayout:
  columns: 3  # 每行显示的分类数量 (2, 3, 4)
extraCSSFiles:
  - /pagefind/pagefind-ui.css
externalJSFiles:
  - /js/littlefoot.js
  - /pagefind/pagefind-ui.js
footerExternalLinks:
  - name: GitHub
    link: https://github.com/pawaovo/xiaoweigeblog
    icon: /img/github.svg
# giscus 评论系统配置 - 请将下面的 YOUR_REPO_ID 和 YOUR_CATEGORY_ID 替换为实际值
giscus:
  repo: pawaovo/xiaoweigeblog  # 您的GitHub仓库
  repoId: R_kgDOPNgxJg  # 从 https://giscus.app 获取，格式如：R_kgDOxxxxxxxx
  category: General
  categoryId: DIC_kwDOPNgxJs4Cu_Sh  # 从 https://giscus.app 获取，格式如：DIC_kwDOxxxxxxxx
  mapping: og:title
  strict: 0
  reactionsEnabled: 1
  emitMetadata: 1
  inputPosition: top
  theme: "https://blog.xiaoweigezzz.xyz/css/giscus_noborder.css"
